sonar.projectKey=OWNER_devops-assessment
sonar.organization=OWNER
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=reports/junit.xml
