apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-service

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: devops-assessment
