apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: devops-service-dev


images:
- name: ghcr.io/OWNER/devops-service
  newTag: latest

patches:
- patch: |
    - op: replace
      path: /spec/maxReplicas
      value: 3
  target:
    kind: HorizontalPodAutoscaler
    name: devops-service
labels:
- includeSelectors: true
  pairs:
    environment: development
